const workouts={
legs:{title:"يوم الأرجل 🦵",exercises:[
["Warm-up","إحماء","fajr-sitting.png","صحّي الأرجل أول. حركة مرتبة وبعدين نبدأ الشغل الحقيقي."],
["Hip Thrust","دفع الورك","fajr-main.png","ارفعي بتحكم واثبتي فوق. مجلس إدارة المكوة يطلب جودة بالتنفيذ، مو عدات والسلام. 😭"],
["RDL","الرفعة الرومانية","fajr-pose.png","نزول هادئ وظهر ثابت. هنا يبان شغل الرجلين والتناسق الحلو بين خصرك وفخوذك. خلصنا المدح، كملي."],
["Kick Back","ركلة خلفية","fajr-mirror.png","كل عدة استثمار إضافي في مكوتك. الاستثمار أصلًا ناجح، بس الآنسة فجر طماعة وتبيها أحلى. 😭"],
["Abduction","فتح الورك","fajr-squat.png","آخر مرحلة. تحكمي بالحركة. وبعدها مسموح نظرة سريعة للمراية… سريعة يا فجر، مو جلسة تصوير."]
],end:`<section class="finish"><h2>Leg Day Complete 🦵✨</h2><p>الأرجل: نجت بصعوبة ✅</p><p>المكوة: أخذت حقها 🍑</p><div class="final-rule">💋 فحص الجودة النهائي: أيوه… الآن المكوة مناسبة للتبويس.</div><button class="btn primary" onclick="home()">الرئيسية</button></section>`},
chest:{title:"صدر + تراي 💪",exercises:[
["Dumbbell Bench Press","ضغط صدر بالدمبل","fajr-main.png","نزول بتحكم وادفعي للأعلى. ركزي على الصدر يا فجر… والموقع بيحاول يركز على التكنيك فقط. نحاول. 😭"],
["Pec Deck / Chest Fly","تفتيح صدر جهاز","fajr-pose.png","افتحي بتحكم واجمعي قدامك. أهم شيء الشد يكون في الصدر. الإدارة تؤكد أن هذه جملة تدريبية بحتة. 😇"],
["Dumbbell Front Raise","رفع أمامي بالدمبل","fajr-sitting.png","ارفعي الدمبل للأمام بتحكم إلى مستوى الكتف تقريبًا. الكتف الأمامي دخل الحصة بدون استئذان."],
["Cable Triceps Extension","تمديد ترايسبس بالكابل","fajr-mirror.png","ثبتي الكوع وخلي الحركة من مفصل الكوع. التراي بدأ يراجع قراراته بالحياة."],
["Cable Triceps Pushdown","دفع ترايسبس بالكابل","fajr-squat.png","الكوع قريب من الجسم، ادفعي لتحت وارجعي بهدوء. لا نبي الجسم كله يشارك في عدة التراي يا معضّلة."],
["Overhead Triceps Extension","تمديد ترايسبس فوق الرأس","fajr-main.png","آخر تمرين. مدّي التراي فوق الرأس بتحكم وخلي الكوع ثابت. بعدها رسميًا ما لك شغل إلا الـPump والمراية. 😭"]
],end:`<section class="finish"><h2>Chest + Triceps Complete 💪✨</h2><p>الصدر: أخذ حقه ✅</p><p>التراي: انتهى رسميًا 💀</p><p>فجر: نجت من الحصة 🎀</p><div class="final-rule">💋 جاهزين للبوس.</div><div class="reaction"><b>فجر:</b> «وش اللي جاهز بالضبط؟»<br><b>الموقع:</b> «الصدر والتراي طبعًا، وش حسبتي؟ 😇»<br><b>🚨 الإدارة:</b> اقفلوا الموقع.</div><button class="btn primary" onclick="home()">الرئيسية</button></section>`}};
let w=null,step=0,mirrorCount=0;
function home(){w=null;document.getElementById("app").innerHTML=`<section class="hero"><div><span class="pill">FAJR GYM ✦ نادي فجر</span><h1>👑 أهلاً يا معضّلة</h1><p>وش بنعذّب اليوم؟ الدلع مسموح، الهروب لا.</p></div><img src="fajr-main.png"></section><section class="days"><button class="day-card" onclick="choose('legs')"><strong>🦵 يوم الأرجل</strong><span>5 مراحل • Leg Day</span></button><button class="day-card" onclick="choose('chest')"><strong>💪 صدر + تراي</strong><span>6 تمارين • Chest + Triceps</span></button><div class="locked">🔒 باقي الأيام بنضيفها يوم بيوم</div></section>`}
function choose(k){w=k;document.getElementById("app").innerHTML=`<section class="outfit"><div><span class="pill">${workouts[k].title}</span><h2>اختاري الأوتفيت 🎀</h2><p>سوتيانا رياضية + ليغينز. لأن اللون طبعًا قرار مصيري.</p><div class="outfit-buttons"><button onclick="outfit(this,'الوردي؟ جاية تتمرنين وتسوين مشاكل بنفس الوقت. 😭')">🩷 وردي</button><button onclick="outfit(this,'الأسود؟ واضح اليوم الأوزان هي اللي لازم تخاف. 🖤')">🖤 أسود</button><button onclick="outfit(this,'الأبيض؟ بريئة بالأوتفيت فقط. 🤍')">🤍 أبيض</button></div><div id="oc" class="comment">اختاري اللون أول يا فجر.</div><button class="btn primary" onclick="start()">ابدئي التمرين 💪</button><button class="btn ghost" onclick="home()">رجوع</button></div><img src="fajr-pose.png"></section>`}
function outfit(b,t){document.querySelectorAll(".outfit-buttons button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");document.getElementById("oc").textContent=t}
function start(){step=0;mirrorCount=0;render()}
function render(){let x=workouts[w].exercises[step];document.getElementById("app").innerHTML=`<section class="workout"><div class="progress"><span style="width:${(step+1)/workouts[w].exercises.length*100}%"></span></div><div class="stage-label">${step+1} / ${workouts[w].exercises.length} • ${workouts[w].title}</div><img src="${x[2]}"><h2>${x[0]}</h2><h3>${x[1]}</h3><p>${x[3]}</p><div id="r" class="comment"></div><div class="actions"><button class="btn primary" onclick="done()">✅ خلصت</button><button class="btn mirror" onclick="mirror()">🪞 بشوف النتيجة</button><button class="btn lazy" onclick="lazy()">😭 مالي خلق</button></div></section>`}
function done(){if(step<workouts[w].exercises.length-1){step++;render()}else document.getElementById("app").innerHTML=workouts[w].end}
function mirror(){mirrorCount++;document.getElementById("r").textContent=w==="legs"?(mirrorCount===1?"إيه، للحين حلوة. المكوة ما اختفت من آخر مجموعة. ارجعي تمرني. 😭":`هذه النظرة رقم ${mirrorCount}. مكوتك ما راح تكبر خلال دقيقتين يا فجر. 💀`):(mirrorCount===1?"إيه الـPump موجود. لا، ما يحتاج فحص كل دقيقتين يا فجر. 😭":`هذه النظرة رقم ${mirrorCount}. الصدر والتراي للحين مكانهم، ارجعي كملي. 💀`)}
function lazy(){let a=["طلب الدلع وصل وتم رفضه. كملي. 😭","أنتِ اللي اخترتي التمرين، تحملي قراراتك.","خذي نفس واشربي موية وكملي يا معضّلة. 💪"];document.getElementById("r").textContent=a[Math.floor(Math.random()*a.length)]}home();